# GitHub Funding Links
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Support the maintainer
custom:
  - https://samin-yasar.dev/support

# Open Collective (if applicable)
# open_collective: username

# Buy Me a Coffee (if applicable)
# buy_me_a_coffee: username

# Ko-fi (if applicable)
# ko_fi: username

# Patreon (if applicable)
# patreon: username

# GitHub Sponsors (if applicable)
# github: Samin-yasar
